version: '3'

services:
  my-flask-app:
    build: ./app
    ports:
      - "5000"
    restart: always


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: always

    depends_on:
      - my-flask-app
